/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyewaan_PC;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class tb_pc extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    /**
     * Creates new form tb_pc
     */
    public tb_pc() {   
        initComponents();
        bersih();
        tampilData();
        setLocationRelativeTo(this);
    }
    private void bersih(){
        textkode.setText(null);
        textmerk.setText(null);
        textwarna.setText(null);
        
    }
    //inner class tampil data
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("kode_pc");
        mod.addColumn("merk");
        mod.addColumn("warna");
        tabel.setModel(mod);
        Connection conn=koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL ="select * from tb_pc";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                res.getString("kode_pc"),
                res.getString("merk"),
                res.getString("warna"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
}
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textkode = new javax.swing.JTextField();
        textmerk = new javax.swing.JTextField();
        textwarna = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kode_pc");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Merk");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Warna");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel1.add(textkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 112, -1));

        textmerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmerkActionPerformed(evt);
            }
        });
        jPanel1.add(textmerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 112, -1));
        jPanel1.add(textwarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 112, -1));

        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        btnread.setText("READ");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        jPanel1.add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("DATA KOMPUTER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        kembali.setBackground(new java.awt.Color(0, 255, 0));
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 30));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 580, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textmerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textmerkActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        FormUtama xx;
        xx = new FormUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int i =tabel.getSelectedRow();
        if(i== -1) {
            return;
        }
        
        String kode_pc = (String)mod.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_pc WHERE kode_pc= ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, kode_pc);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Dihapus");
            }catch (SQLException e){
                System.out.println(e);
            }
        }
        if (question == JOptionPane.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
    try{
        String sql = "UPDATE tb_pc SET merk ='"+textmerk.getText()+"', warna='"+textwarna.getText()+"'WHERE kode_pc='"+textkode.getText()+"'";
        java.sql.Connection conn = (Connection)koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.execute();
        JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUPDATE");
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"DATA GAGAL DISIMPAN"+ e.getMessage());
    }
    tampilData();
    bersih();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
            ("insert into tb_pc (kode_pc, merk, warna)value(?, ?, ?)");
            stmt.setString(1, textkode.getText());
            stmt.setString(2, textmerk.getText());
            stmt.setString(3, textwarna.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnreadActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
      try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
            ("insert into tb_pc (kode_pc, merk, warna)value(?, ?, ?)");
            stmt.setString(1, textkode.getText());
            stmt.setString(2, textmerk.getText());
            stmt.setString(3, textwarna.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Tambah ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_btncreateActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         try{
               Connection conn = koneksi.getConnection();
               int row = tabel.getSelectedRow();
               String tabel_klik = (tabel.getModel().getValueAt(row, 0).toString());
               java.sql.Statement stmt = conn.createStatement();
               java.sql.ResultSet sql = stmt.executeQuery("select * from tb_pc where  kode_pc = '"+tabel_klik+"'");
               if (sql.next()){
                   String kode_pc=sql.getString("kode_pc");
                   textkode.setText(kode_pc);
                   String merk=sql.getString("merk");
                   textmerk.setText(merk);
                   String warna=sql.getString("warna");
                   textwarna.setText(warna);
               }
           }catch (SQLException e){}
    }//GEN-LAST:event_tabelMouseClicked
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_pc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tb_pc().setVisible(true);
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField textkode;
    private javax.swing.JTextField textmerk;
    private javax.swing.JTextField textwarna;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void autonumber() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
