/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyewaan_PC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ACER
 */
public class tb_penyewaan extends javax.swing.JFrame {
     DefaultTableModel mod;
    private String SQL;
    /**
     * Creates new form tb_penyewaan
     */
    public tb_penyewaan() {
        initComponents();
        bersih();
        tampilData();
        setLocationRelativeTo(this);
    }
    private void bersih(){
        textid.setText(null);
        textnama.setText(null);
        textalamat.setText(null);
        textjeniskelamin.setText(null);
        texttgllahir.setText(null);
        textnohp.setText(null);
        textsewa.setText(null);
        textmerkwarna.setText(null);
    }
    //inner class tampil data
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("id");
        mod.addColumn("nama_penyw");
        mod.addColumn("alamat_penyw");
        mod.addColumn("jenis_kelamin");
        mod.addColumn("tgl_lahir");
        mod.addColumn("no_hp");
        mod.addColumn("tgl_penyw");
        mod.addColumn("merk");
        jTable1.setModel(mod);
        Connection conn=koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select*from tb_penyewaan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama_penyw"),
                    res.getString("alamat_penyw"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("no_hp"),
                    res.getString("tgl_penyw"),
                    res.getString("merk"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textid = new javax.swing.JTextField();
        textnama = new javax.swing.JTextField();
        textalamat = new javax.swing.JTextField();
        textjeniskelamin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        texttgllahir = new javax.swing.JTextField();
        textnohp = new javax.swing.JTextField();
        textsewa = new javax.swing.JTextField();
        textmerkwarna = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btncetak = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATA PENYEWAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 11, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLabel3.setText("NAMA PENYEWA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel4.setText("ALAMAT PENYEWA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(textid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 125, -1));
        getContentPane().add(textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 84, 128, -1));
        getContentPane().add(textalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 122, 128, -1));
        getContentPane().add(textjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 160, 128, -1));

        jLabel6.setText("TANGGAL LAHIR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 49, -1, -1));

        jLabel7.setText("NO HP");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 87, -1, -1));

        jLabel8.setText("TANGGAL PENYEWAAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel9.setText("MERK");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 163, -1, -1));
        getContentPane().add(texttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 46, 155, -1));
        getContentPane().add(textnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 84, 155, -1));
        getContentPane().add(textsewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 122, 155, -1));
        getContentPane().add(textmerkwarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 160, 155, -1));

        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        getContentPane().add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 214, -1, -1));

        btnread.setText("READ");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        getContentPane().add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 214, -1, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 214, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 214, -1, -1));

        btnkembali.setText("KEMBALI");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 214, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 670, 120));

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 214, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\white-gold-geometric-pattern-background-vector_53876-140726.jpg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        FormUtama xx;
        xx = new FormUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
         try{
            Connection conn= koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
            ("insert into tb_penyewaan(id, nama_penyw, alamat_penyw,jenis_kelamin, tgl_lahir, no_hp, tgl_penyw, merk)value(?, ?, ?, ?, ?, ?, ?, ?)");
            stmt.setString(1, textid.getText());
            stmt.setString(2, textnama.getText());
            stmt.setString(3, textalamat.getText());
            stmt.setString(4, textjeniskelamin.getText());
            stmt.setString(5, texttgllahir.getText());
            stmt.setString(6, textnohp.getText());
            stmt.setString(7, textsewa.getText());
            stmt.setString(8, textmerkwarna.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di TAMBAH", "Pesan",JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int i =jTable1.getSelectedRow();
        if(i== -1) {
            return;
        }
        
        String id = (String)mod.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_penyewaan WHERE id= ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, id);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Dihapus");
            }catch (SQLException e){
                System.out.println(e);
            }
        }
        if (question == JOptionPane.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report2.jasper"), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (JRException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        try{
            Connection conn= koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
            ("insert into tb_penyewaan(id, nama_penyw, alamat_penyw,jenis_kelamin, tgl_lahir, no_hp, tgl_penyw, merk)value(?, ?, ?, ?, ?, ?, ?, ?)");
            stmt.setString(1, textid.getText());
            stmt.setString(2, textnama.getText());
            stmt.setString(3, textalamat.getText());
            stmt.setString(4, textjeniskelamin.getText());
            stmt.setString(5, texttgllahir.getText());
            stmt.setString(6, textnohp.getText());
            stmt.setString(7, textsewa.getText());
            stmt.setString(8, textmerkwarna.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan", "Pesan",JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnreadActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
     try{
        String sql = "UPDATE tb_penyewaan SET nama_penyw ='"+textnama.getText()+"', alamat_penyw='"+textalamat.getText()+"', jenis_kelamin='"+textjeniskelamin.getText()+"', tgl_lahir='"+texttgllahir.getText()+"', no_hp='"+textnohp.getText()+"', tgl_penyw='"+textsewa.getText()+"', merk='"+textmerkwarna.getText()+"'WHERE id='"+textid.getText()+"'";
        java.sql.Connection conn = (Connection)koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.execute();
        JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUPDATE");
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"DATA GAGAL DISIMPAN"+ e.getMessage());
    }
    tampilData();
    bersih();        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
    Connection conn = koneksi.getConnection();
    int row = jTable1.getSelectedRow();
    String tabel_klik = (jTable1.getModel().getValueAt(row, 0).toString());
    java.sql.Statement stmt = conn.createStatement();
    java.sql.ResultSet sql = stmt.executeQuery("select * from tb_penyewaan where  id = '"+tabel_klik+"'");
        if (sql.next()){
            String id=sql.getString("id");
            textid.setText(id);
            String nama_penyw=sql.getString("nama_penyw");
            textnama.setText(nama_penyw);
            String alamat_penyw=sql.getString("alamat_penyw");
            textalamat.setText(alamat_penyw);
            String jenis_kelamin=sql.getString("jenis_kelamin");
            textjeniskelamin.setText(jenis_kelamin);
            String tgl_lahir=sql.getString("tgl_lahir");
            texttgllahir.setText(tgl_lahir);
            String no_hp=sql.getString("no_hp");
            textnohp.setText(no_hp);
            String tgl_penyw=sql.getString("tgl_penyw");
            textsewa.setText(tgl_penyw);
            String merk=sql.getString("merk");
            textmerkwarna.setText(merk);
            
               }
           }catch (SQLException e){} 
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tb_penyewaan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textalamat;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textjeniskelamin;
    private javax.swing.JTextField textmerkwarna;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textnohp;
    private javax.swing.JTextField textsewa;
    private javax.swing.JTextField texttgllahir;
    // End of variables declaration//GEN-END:variables
}
