/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyewaan_PC;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ACER
 */
public class tb_pegawai extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    /**
     * Creates new form tb_pegawai
     */
    public tb_pegawai() {
        initComponents();
        bersih();
        tampilData();
        setLocationRelativeTo(this);
    }
    private void bersih(){
        textid.setText(null);
        textnama.setText(null);
        textalamat.setText(null);
        textjeniskelamin.setText(null);
        textno.setText(null);
    }
    //inner class tampil data
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("id");
        mod.addColumn("nama_pegawai");
        mod.addColumn("alamat_pegawai");
        mod.addColumn("jenis_kelamin");
        mod.addColumn("no_hp");
        jTable1.setModel(mod);
        Connection conn=koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select*from tb_pegawai";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama_pegawai"),
                    res.getString("alamat_pegawai"),
                    res.getString("jenis_kelamin"),
                    res.getString("no_hp"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textid = new javax.swing.JTextField();
        textnama = new javax.swing.JTextField();
        textalamat = new javax.swing.JTextField();
        textjeniskelamin = new javax.swing.JTextField();
        textno = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btncetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATA PEGAWAI");

        jLabel2.setText("ID");

        jLabel3.setText("NAMA PEGAWAI");

        jLabel4.setText("ALAMAT PEGAWAI");

        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setText("NO HP");

        textid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidActionPerformed(evt);
            }
        });

        textalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textalamatActionPerformed(evt);
            }
        });

        textno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnoActionPerformed(evt);
            }
        });

        btnkeluar.setBackground(new java.awt.Color(51, 255, 51));
        btnkeluar.setText("KEMBALI");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btncreate.setBackground(new java.awt.Color(255, 255, 51));
        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        btnread.setBackground(new java.awt.Color(0, 204, 0));
        btnread.setText("READ");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 204, 51));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btncetak.setBackground(new java.awt.Color(0, 255, 255));
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textid)
                                    .addComponent(textnama)
                                    .addComponent(textalamat)
                                    .addComponent(textjeniskelamin)
                                    .addComponent(textno, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnread)
                                .addGap(379, 379, 379)
                                .addComponent(btncetak)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btncreate)
                        .addGap(43, 43, 43)
                        .addComponent(btnupdate)
                        .addGap(38, 38, 38)
                        .addComponent(btndelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkeluar)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnkeluar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnread)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btncetak)
                    .addComponent(btncreate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidActionPerformed

    private void textalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textalamatActionPerformed

    private void textnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnoActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        FormUtama xx;
        xx = new FormUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
       try{
           Connection conn= koneksi.getConnection();
           PreparedStatement stmt = conn.prepareStatement
        ("insert into tb_pegawai(id, nama_pegawai, alamat_pegawai, jenis_kelamin, no_hp)value(?, ?, ?, ?, ?)");
           stmt.setString(1, textid.getText());
           stmt.setString(2, textnama.getText());
           stmt.setString(3, textalamat.getText());
           stmt.setString(4, textjeniskelamin.getText());
           stmt.setString(5, textno.getText());
           stmt.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Berhasil di Tambah", "Pesan",JOptionPane.INFORMATION_MESSAGE);
           tampilData();
           bersih();
       }catch (SQLException e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int i =jTable1.getSelectedRow();
        if(i== -1) {
            return;
        }
        
        String id = (String)mod.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_pegawai WHERE id= ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, id);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Dihapus");
            }catch (SQLException e){
                System.out.println(e);
            }
        }
        if (question == JOptionPane.CANCEL_OPTION){
            
        }     
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
      try{
         JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report1.jasper"), null, koneksi.getConnection());
         JasperViewer.viewReport(jp, false); 
         
      }catch (JRException e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
    }//GEN-LAST:event_btncetakActionPerformed
 
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
         try{
        String sql = "UPDATE tb_pegawai SET nama_pegawai ='"+textnama.getText()+"', alamat_pegawai='"+textalamat.getText()+"', jenis_kelamin='"+textjeniskelamin.getText()+"', no_hp='"+textno.getText()+"'WHERE id='"+textid.getText()+"'";
        java.sql.Connection conn = (Connection)koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.execute();
        JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUPDATE");
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"DATA GAGAL DISIMPAN"+ e.getMessage());
    }
    tampilData();
    bersih();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        try{
            Connection conn= koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
            ("insert into tb_pegawai(id, nama_pegawai, alamat_pegawai, jenis_kelamin, no_hp)value(?, ?, ?, ?, ?)");
            stmt.setString(1, textid.getText());
            stmt.setString(2, textnama.getText());
            stmt.setString(3, textalamat.getText());
            stmt.setString(4, textjeniskelamin.getText());
            stmt.setString(5, textno.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan", "Pesan",JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnreadActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 try{
    Connection conn = koneksi.getConnection();
    int row = jTable1.getSelectedRow();
    String tabel_klik = (jTable1.getModel().getValueAt(row, 0).toString());
    java.sql.Statement stmt = conn.createStatement();
    java.sql.ResultSet sql = stmt.executeQuery("select * from tb_pegawai where  id = '"+tabel_klik+"'");
        if (sql.next()){
            String id=sql.getString("id");
            textid.setText(id);
            String nama_pegawai=sql.getString("nama_pegawai");
            textnama.setText(nama_pegawai);
            String alamat_pegawai=sql.getString("alamat_pegawai");
            textalamat.setText(alamat_pegawai);
            String jenis_kelamin=sql.getString("jenis_kelamin");
            textjeniskelamin.setText(jenis_kelamin);
            String no_hp=sql.getString("no_hp");
            textno.setText(no_hp);
            
               }
           }catch (SQLException e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tb_pegawai().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textalamat;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textjeniskelamin;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textno;
    // End of variables declaration//GEN-END:variables
}
